name: PLC Project Backup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backup:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify Structure
      run: |
        Get-ChildItem -Recurse